### PR TITLE
chore: add jest versions v28.1.1 through v29.3.1

### PR DESCRIPTION
**Pull request by gregmagolan**
Resolves https://github.com/aspect-build/rules_jest/issues/64

"+31,488 −0" 😂  Do I get a GitHub achievement for this one?

### CODE REVIEW

**Comment by jbedard** [comment]
Can we not fetch these instead? lol

Only checkin the hashes and download them?

**Comment by gregmagolan** [comment]
> Can we not fetch these instead? lol
> 
> Only checkin the hashes and download them?

To make the transitive deps pinned and deterministic its best to check-in the whole lock file

**Review by kormide — APPROVED** [review]

**Comment by jbedard** [comment]
> To make the transitive deps pinned and deterministic its best to check-in the whole lock file.

Aren't the ones in a specific git tag/hash or npmjs.org package be pinned?

IMO checking in anything that must be constantly updated (adding new versions) is a hassle. I think we've concluded we have to do it, but a list of versions+hashes is far nicer then entire lockfiles or libraries...

**Comment by gregmagolan** [comment]
The `jest` npm package has a ton on transitive deps so its more than just one hash to worry about

**Comment by jbedard** [comment]
Doesn't lockfile pin all those though? If the lockfile doesn't change then none of those transitive deps change... if we checkin a lockfile hash wouldn't that guarantee nothing changed?

**Pull request merged**
