### PR TITLE
Add quotes around config path

### PR DESCRIPTION
**Pull request by pwalker**
I can't tell if this is actually a good fix, let me know!

### Type of change

- Bug fix (change which fixes an issue): https://github.com/aspect-build/rules_jest/issues/151

### Test plan

- New test cases added: I copied the `simple/` folder to `(simple_group)/` to ensure all the different types of configs pass.

### CODE REVIEW

**Comment by vihangm** [comment]
I think single quotes are probably better than double quotes so that the shell doesn't try to do any expansion!
However either way this works well!

**Comment by philkuz** [comment]
@gregmagolan Hey Greg, hope I'm tagging the right maintainer. We recently ran into this same issue on my team (cc @vihangm) and would love to see this fix in!

**Review by gregmagolan — APPROVED** [review]
Thanks for the fix!

**Comment by gregmagolan** [comment]
Cutting a v0.19.6 release with this fix since we haven't had a release in a while.

**Pull request merged**
