### PR TITLE
chore: bzlmod

### LINKED ISSUE #79: [FR]: Support bzlmod
### What is the current behavior?

_No response_

### Describe the feature

I'm not sure if these rules support bzlmod. If they do, could you update the documentation with instructions on how to use it similar to [rules_js](https://github.com/aspect-build/rules_js/releases/tag/v1.13.0)?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #79

### CODE REVIEW

**Comment by alexeagle** [comment]
Maybe this needs to wait until the node_modules isn't vendored?

**Comment by alexeagle** [comment]
@gregmagolan rebased on the removal of vendored jest, but I'm stumped on the test failure under bzlmod...

**Comment by alexeagle** [comment]
it was rules_js registering an old version of node :(

**Comment by gregmagolan** [comment]
rules_js 1.24.1 resolves the bzlmod node toolchain issue

**Review by gregmagolan — APPROVED** [review]

**Pull request merged**
